### ISSUE TITLE
Error in nginx/conf.d using Let's Encrypt

### ISSUE THREAD

**Issue by fswm3i** [OsiriX-Foundation/KheopsNginx#2]
Hi,
i'm trying to set up Kheops securely in docker, however the reverse proxy container always fails while starting. 
Before, I was sucessfully running it locally and unsecured. Following the documentation for running the ngix proxy-container with the flag "-letsencrypt" I made all changes to the compose files. "our.server.me" is available from the internet and has a valid let's encrypt certificate. Browsing "https://our.server.me:8443" from outside of the network opens the secured page of the Keycloak instance as expected. I tried to make sense of the script.sh which seems to populate the nginx/conf.d, sadly to no avail. I attached the log of the failing container below in hopes of someone helping me fix the problem.

`
environment variable KHEOPS_ROOT_URL OK
environment variable KHEOPS_DICOMWEB_PROXY_HOST OK
environment variable KHEOPS_DICOMWEB_PROXY_PORT OK
environment variable KHEOPS_AUTHORIZATION_HOST OK
environment variable KHEOPS_AUTHORIZATION_PORT OK
environment variable KHEOPS_PACS_PEP_HOST OK
environment variable KHEOPS_PACS_PEP_PORT OK
environment variable KHEOPS_ZIPPER_HOST OK
environment variable KHEOPS_ZIPPER_PORT OK
environment variable KHEOPS_UI_HOST OK
environment variable KHEOPS_UI_PORT OK
environment variable KHEOPS_OIDC_PROVIDER OK
environment variable LETS_ENCRYPT_EMAIL OK
all nginx secrets and all env var OK
Ending setup NGINX secrets and env var
[INFO] : Missing KHEOPS_REVERSE_PPROXY_ENABLE_ELASTIC environment variable. Elastic is not enable.
Generating RSA private key, 4096 bit long modulus (2 primes)
............................................................++++
......................................................................................................................++++
e is 65537 (0x010001)
Signature ok
subject=C = PT, ST = World, L = World, O = our.server.me, OU = kheops lda, CN = our.server.me
Getting Private key
Setting up watches.
Watches established.
nginx: [emerg] "proxy_pass" cannot have URI part in location given by regular expression, or inside named location, or inside "if" statement, or inside "limit_except" block in /etc/nginx/conf.d/kheops.conf:266`

**Comment by spalte** [comment]
Hi,

Thanks for your message.

From that log my first instinct is that there must be something wrong with the KHEOPS_ROOT_URL environment variable.

That variable gets copied into the nginx configuration file right after the proxy_pass directive on line 266, and it looks like nginx gets confused parsing that line.

Hope this sets you on the right track, and please respond if you run into any more trouble.

Cheers,
Joël

**Comment by fswm3i** [comment]
Thanks for the quick response, you are absolutely right, "my.domain.me/" and "my.domain.me" are not the same.
